language: csharp
mono: none
dotnet: 2.2
solution: HelloWorld.sln
script:
  - dotnet restore
  - dotnet test --filter FullyQualifiedName~UnitTest1
  - echo "Lint check"
  - dotnet test
  - dotnet build
