language: csharp
mono: none
dotnet: 2.2
solution: HelloWorld.sln
script:
  - dotnet restore 2>&1 | tee -a $TRAVIS_BUILD_DIR/build.log 
  - dotnet test --filter FullyQualifiedName~UnitTest1 2>&1 | tee -a $TRAVIS_BUILD_DIR/build.log
  - echo "Lint check" 2>&1 | tee -a $TRAVIS_BUILD_DIR/build.log
  - dotnet test 2>&1 | tee -a $TRAVIS_BUILD_DIR/build.log
  - dotnet build 2>&1 | tee -a $TRAVIS_BUILD_DIR/build.log
#  - dotnet pack -v d -o $TRAVIS_BUILD_DIR/nupkg 2>&1 | tee -a $TRAVIS_BUILD_DIR/build.log
  - tar czf $TRAVIS_BUILD_DIR/package.tar.gz $TRAVIS_BUILD_DIR/build.log $TRAVIS_BUILD_DIR/HelloWorldSolution
  
deploy:
  provider: releases
  api_key: $ACCESS_TOKEN
  file: package.tar.gz
  skip_cleanup: true
  on:
    tags: true
    branch: travis
